Repository Nova-Storage/starca-server, pull requests merged in 2023-03, with the labels that each got.

#1 Added Jaimeen's set up for app.js. Added Jaimeen's db.js
  app.js
  db.js
  package-lock.json
  package.json
Labels: enhancement

#3 Fixed folder import name
  app.js
Labels: enhancement

#4 Added scripts to automatically get SSL certificates and enable https …
  .ebextensions/00_install_certbot.config
  .ebextensions/01_open_https_port.config
  .ebextensions/02_grant_executable_rights.config
  .ebextensions/03_renew_ssl_certificate_cron_job.config
  .platform/hooks/postdeploy/00_get_certificate.sh
  README.md
  app.js
Labels: enhancement

#5 Fix https
  .platform/hooks/postdeploy/00_get_certificate.sh
  app.js
Labels: bug

#6 Increased server_names_hash_bucket_size to 128
  .ebextensions/nginx/conf.d/myconf.conf
Labels: bug

#7 Updaded server names hash bucket size to 512
  .ebextensions/nginx/conf.d/myconf.conf
Labels: bug

#8 Moved nginx directory under .platform
  .ebextensions/nginx/conf.d/myconf.conf
  .platform/hooks/postdeploy/nginx/conf.d/myconf.conf
Labels: bug

#9 Fixing .conf syntax
  .platform/hooks/postdeploy/nginx/conf.d/myconf.conf
Labels: bug

#10 Re-added nginx directory under .ebextensions
  .ebextensions/nginx/conf.d/myconf.conf
Labels: bug

#11 Changed server names hash bucket size to 128
  .ebextensions/nginx/conf.d/myconf.conf
  .platform/hooks/postdeploy/nginx/conf.d/myconf.conf
Labels: bug

#12 Added a new config file
  .ebextensions/04_server_names_size.config
Labels: bug

#13 Cleaned up unused scripts. Updated README
  .ebextensions/00_install_certbot.config
  .ebextensions/01_open_https_port.config
  .ebextensions/02_grant_executable_rights.config
  .ebextensions/03_renew_ssl_certificate_cron_job.config
  .ebextensions/04_server_names_size.config
  .ebextensions/nginx/conf.d/myconf.conf
  .platform/hooks/postdeploy/00_get_certificate.sh
  .platform/hooks/postdeploy/nginx/conf.d/myconf.conf
  README.md
  app.js
Labels: documentation

#14 Added header for cors
  .platform/nginx/conf.d/elasticbeanstalk/cors.conf
Labels: bug

#15 New cors config file
  .platform/nginx/conf.d/cors.conf
  .platform/nginx/conf.d/elasticbeanstalk/new-cors.conf
Labels: bug

#16 Actual new conf file
  .platform/nginx/conf.d/elasticbeanstalk/cors.conf
  .platform/nginx/conf.d/elasticbeanstalk/new-cors.conf
Labels: bug

#17 Replace cors file
  .platform/nginx/conf.d/elasticbeanstalk/cors.conf
  .platform/nginx/conf.d/elasticbeanstalk/new-cors.conf
Labels: bug

#18 New cors config file
  .ebextensions/00_add_cors_config.yaml
  .platform/nginx/conf.d/elasticbeanstalk/cors.conf
Labels: bug

#19 Adding cors
  app.js
  package-lock.json
  package.json
Labels: bug
